/* eslint-disable max-lines */

module.exports.baseGet = {
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  body: {
    message: 'Hello from baseGet, FilesController',
  },
  files: undefined,
  buffered: true,
  header:
      {
        server: 'FilesApi',
        'content-encoding': 'gzip',
        'content-type': 'application/json',
        date: 'Tue, 13 Nov 2018 17:28:14 GMT',
        connection: 'close',
        'transfer-encoding': 'chunked',
      },
  statusCode: 200,
  status: 200,
  statusType: 2,
  info: false,
  ok: true,
  redirect: false,
  clientError: false,
  serverError: false,
  error: false,
  created: false,
  accepted: false,
  noContent: false,
  badRequest: false,
  unauthorized: false,
  notAcceptable: false,
  forbidden: false,
  notFound: false,
};

module.exports.createCollectionPost = {
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  body: {
    message: 'Created a new collection mochaTest',
  },
  files: undefined,
  buffered: true,
  header: {
    server: 'FilesApi',
    'content-encoding': 'gzip',
    'content-type': 'application/json',
    accepts: 'POST',
    date: 'Tue, 13 Nov 2018 19:06:19 GMT',
    connection: 'close',
    'transfer-encoding': 'chunked',
  },
  statusCode: 201,
  status: 201,
  statusType: 2,
  info: false,
  ok: true,
  redirect: false,
  clientError: false,
  serverError: false,
  error: false,
  created: true,
  accepted: false,
  noContent: false,
  badRequest: false,
  unauthorized: false,
  notAcceptable: false,
  forbidden: false,
};

module.exports.dropCollectionDelete = {
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  body: {
    message: '',
  },
  files: undefined,
  buffered: true,
  header: {
    server: 'FilesApi',
    'content-encoding': 'gzip',
    'content-type': 'application/json',
    accepts: 'DELETE',
    date: 'Tue, 13 Nov 2018 19:16:19 GMT',
    connection: 'close',
    'transfer-encoding': 'chunked',
  },
  statusCode: 204,
  status: 204,
  statusType: 2,
  info: false,
  ok: true,
  redirect: false,
  clientError: false,
  serverError: false,
  error: false,
  created: true,
  accepted: false,
  noContent: false,
  badRequest: false,
  unauthorized: false,
  notAcceptable: false,
  forbidden: false,
};

module.exports.getDocPost = {
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  body: [{
    _id: '5be9ef05ebeb4807ecd8f82d',
    colname: 'mochaTest',
    fileTitle: 'mochaTest',
    fileLink: 'http://mochaTest.co.uk/',
    author: 'mochaTest',
    deleted: false,
  }],
  files: undefined,
  buffered: true,
  header: {
    server: 'FilesApi',
    'content-encoding': 'gzip',
    'content-type': 'application/json',
    accepts: 'POST',
    date: 'Tue, 13 Nov 2018 19:16:19 GMT',
    connection: 'close',
    'transfer-encoding': 'chunked',
  },
  statusCode: 200,
  status: 200,
  statusType: 2,
  info: false,
  ok: true,
  redirect: false,
  clientError: false,
  serverError: false,
  error: false,
  created: true,
  accepted: false,
  noContent: false,
  badRequest: false,
  unauthorized: false,
  notAcceptable: false,
  forbidden: false,
};

module.exports.addDocPost = {
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  body: {
    message: 'Successfully uploaded',
  },
  files: undefined,
  buffered: true,
  header: {
    server: 'FilesApi',
    'content-encoding': 'gzip',
    'content-type': 'application/json',
    accepts: 'POST',
    date: 'Tue, 13 Nov 2018 19:06:19 GMT',
    connection: 'close',
    'transfer-encoding': 'chunked',
  },
  statusCode: 201,
  status: 201,
  statusType: 2,
  info: false,
  ok: true,
  redirect: false,
  clientError: false,
  serverError: false,
  error: false,
  created: true,
  accepted: false,
  noContent: false,
  badRequest: false,
  unauthorized: false,
  notAcceptable: false,
  forbidden: false,
};

module.exports.delDocPost = {
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  body: {
    message: '',
    deleted: true,
  },
  files: undefined,
  buffered: true,
  header: {
    server: 'FilesApi',
    'content-encoding': 'gzip',
    'content-type': 'application/json',
    accepts: 'PUT',
    date: 'Tue, 13 Nov 2018 19:06:19 GMT',
    connection: 'close',
    'transfer-encoding': 'chunked',
  },
  statusCode: 204,
  status: 204,
  statusType: 2,
  info: false,
  ok: true,
  redirect: false,
  clientError: false,
  serverError: false,
  error: false,
  created: true,
  accepted: false,
  noContent: false,
  badRequest: false,
  unauthorized: false,
  notAcceptable: false,
  forbidden: false,
};

module.exports.getAllPost = {
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  body: [{
    _id: '5be9ef05ebeb4807ecd8f82d',
    colname: 'mochaTest',
    fileTitle: 'mochaTest',
    fileLink: 'http://mochaTest.co.uk/',
    author: 'mochaTest',
    deleted: false,
  }, {
    _id: '4be9ef05ebeb4807ecd8f82d',
    colname: 'mochaTest',
    fileTitle: 'mochaTest1',
    fileLink: 'http://mochaTest1.co.uk/',
    author: 'mochaTest',
    deleted: true,
  }],
  files: undefined,
  buffered: true,
  header: {
    server: 'FilesApi',
    'content-encoding': 'gzip',
    'content-type': 'application/json',
    accepts: 'POST',
    date: 'Tue, 13 Nov 2018 19:16:19 GMT',
    connection: 'close',
    'transfer-encoding': 'chunked',
  },
  statusCode: 200,
  status: 200,
  statusType: 2,
  info: false,
  ok: true,
  redirect: false,
  clientError: false,
  serverError: false,
  error: false,
  created: true,
  accepted: false,
  noContent: false,
  badRequest: false,
  unauthorized: false,
  notAcceptable: false,
  forbidden: false,
};

module.exports.forceDeleteDelete = {
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  body: {
    message: '',
  },
  files: undefined,
  buffered: true,
  header: {
    server: 'FilesApi',
    'content-encoding': 'gzip',
    'content-type': 'multipart/form-data',
    'content-length': 301877,
    accepts: 'DELETE',
    date: 'Tue, 13 Nov 2018 19:06:19 GMT',
    connection: 'close',
    'transfer-encoding': 'chunked',
  },
  statusCode: 204,
  status: 204,
  statusType: 2,
  info: false,
  ok: true,
  redirect: false,
  clientError: false,
  serverError: false,
  error: false,
  created: true,
  accepted: false,
  noContent: false,
  badRequest: false,
  unauthorized: false,
  notAcceptable: false,
  forbidden: false,
};

module.exports.uploadPost = {
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  body: {
    hasBeenSuccessful: true,
    errors: '',
    redirect: 'http://localhost:8082/api/v1/files/addDoc',
    content: {
      message: 'File has been succesfully uploaded',
    },
  },
  file: {
    fieldname: 'image',
    originalname: 'image2.jpg',
    encoding: '7bit',
    mimetype: 'image/jpeg',
    destination: './public/uploads',
    filename: '1542463186053-image2.jpg',
    path: 'public\\uploads\\1542463186053-image2.jpg',
    size: 301195,
  },
  files: undefined,
  buffered: true,
  header: {
    authorization: 'Bearer correctToken',
    server: 'FilesApi',
    'content-encoding': 'gzip',
    contentType: 'multipart/form-data',
    accepts: 'POST',
    date: 'Tue, 13 Nov 2018 19:06:19 GMT',
    connection: 'close',
    'transfer-encoding': 'chunked',
  },
  statusCode: 201,
  status: 201,
  statusType: 2,
  info: false,
  ok: true,
  redirect: false,
  clientError: false,
  serverError: false,
  error: false,
  created: true,
  accepted: false,
  noContent: false,
  badRequest: false,
  unauthorized: false,
  notAcceptable: false,
  forbidden: false,
};
