/* eslint-disable max-lines */

module.exports.baseGet = {
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  body: {
    message: 'Hello from baseGet, EmailController',
  },
  files: undefined,
  buffered: true,
  header:
      {
        server: 'FilesApi',
        'content-encoding': 'gzip',
        'content-type': 'application/json',
        date: 'Tue, 13 Nov 2018 17:28:14 GMT',
        connection: 'close',
        'transfer-encoding': 'chunked',
      },
  statusCode: 200,
  status: 200,
  statusType: 2,
  info: false,
  ok: true,
  redirect: false,
  clientError: false,
  serverError: false,
  error: false,
  created: false,
  accepted: false,
  noContent: false,
  badRequest: false,
  unauthorized: false,
  notAcceptable: false,
  forbidden: false,
  notFound: false,
};

module.exports.customerPost = {
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  body: {
    message: 'Email successfully sent to mochaTest',
  },
  files: undefined,
  buffered: true,
  header:
      {
        server: 'FilesApi',
        'content-encoding': 'gzip',
        'content-type': 'application/json',
        date: 'Tue, 13 Nov 2018 17:28:14 GMT',
        connection: 'close',
        'transfer-encoding': 'chunked',
      },
  statusCode: 202,
  status: 202,
  statusType: 2,
  info: false,
  ok: true,
  redirect: false,
  clientError: false,
  serverError: false,
  error: false,
  created: false,
  accepted: false,
  noContent: false,
  badRequest: false,
  unauthorized: false,
  notAcceptable: false,
  forbidden: false,
  notFound: false,
};

module.exports.feedbackPost = {
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  body: {
    message: 'Feedback received',
  },
  files: undefined,
  buffered: true,
  header:
      {
        server: 'FilesApi',
        'content-encoding': 'gzip',
        'content-type': 'application/json',
        date: 'Tue, 13 Nov 2018 17:28:14 GMT',
        connection: 'close',
        'transfer-encoding': 'chunked',
      },
  statusCode: 202,
  status: 202,
  statusType: 2,
  info: false,
  ok: true,
  redirect: false,
  clientError: false,
  serverError: false,
  error: false,
  created: false,
  accepted: false,
  noContent: false,
  badRequest: false,
  unauthorized: false,
  notAcceptable: false,
  forbidden: false,
  notFound: false,
};
