/* eslint-disable max-lines */
/* eslint-disable max-len */
/* eslint-disable max-lines */

module.exports.baseGet = {
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  body: {
    message: 'Hello from baseGet, UserController',
  },
  files: undefined,
  buffered: true,
  header:
      {
        server: 'UsersApi',
        'content-encoding': 'gzip',
        'content-type': 'application/json',
        date: 'Tue, 13 Nov 2018 17:28:14 GMT',
        connection: 'close',
        'transfer-encoding': 'chunked',
      },
  statusCode: 200,
  status: 200,
  statusType: 2,
  info: false,
  ok: true,
  redirect: false,
  clientError: false,
  serverError: false,
  error: false,
  created: false,
  accepted: false,
  noContent: false,
  badRequest: false,
  unauthorized: false,
  notAcceptable: false,
  forbidden: false,
  notFound: false,
};

module.exports.loginPost = {
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  body: {
    firstname: 'mochaTest',
    lastname: 'mochaTest',
    email: 'mochaTest@mocha.com',
    username: 'mochaTest',
    message: 'Successfuly generated Token',
    token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJoYXNoVG9rZW4iOiI1NjQ0N2ZmNWQ4NjJjNGFiYmQzZDNhZDc3ZGM1YjJjNzZlNmQyOWU5NWU4YzE3N2IzNTYxZjdkM2M4ZGZiZjNmIiwiaWF0IjoxNTQyMTQzNDM0LCJleHAiOjE1NDIxNDUyMzR9.XFncaoADuruUorJOllrjK7qe0iZaDSHPy17I7ZxAoK4',
  },
  files: undefined,
  buffered: true,
  header: {
    server: 'UsersApi',
    'content-encoding': 'gzip',
    'content-type': 'application/json',
    accepts: 'POST',
    date: 'Tue, 13 Nov 2018 19:06:19 GMT',
    connection: 'close',
    'transfer-encoding': 'chunked',
  },
  statusCode: 202,
  status: 202,
  statusType: 2,
  info: false,
  ok: true,
  redirect: false,
  clientError: false,
  serverError: false,
  error: false,
  created: true,
  accepted: false,
  noContent: false,
  badRequest: false,
  unauthorized: false,
  notAcceptable: false,
  forbidden: false,
};

module.exports.registerPost = {
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  body: {
    message: 'User mochaTest successfully registered',
  },
  files: undefined,
  buffered: true,
  header: {
    server: 'UsersApi',
    'content-encoding': 'gzip',
    'content-type': 'application/json',
    accepts: 'DELETE',
    date: 'Tue, 13 Nov 2018 19:16:19 GMT',
    connection: 'close',
    'transfer-encoding': 'chunked',
  },
  statusCode: 201,
  status: 201,
  statusType: 2,
  info: false,
  ok: true,
  redirect: false,
  clientError: false,
  serverError: false,
  error: false,
  created: true,
  accepted: false,
  noContent: false,
  badRequest: false,
  unauthorized: false,
  notAcceptable: false,
  forbidden: false,
};

module.exports.createTablePost = {
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  body: {
    message: 'Succesfully created table mochaTest',
  },
  files: undefined,
  buffered: true,
  header: {
    server: 'UsersApi',
    'content-encoding': 'gzip',
    'content-type': 'application/json',
    accepts: 'POST',
    date: 'Tue, 13 Nov 2018 19:06:19 GMT',
    connection: 'close',
    'transfer-encoding': 'chunked',
  },
  statusCode: 201,
  status: 201,
  statusType: 2,
  info: false,
  ok: true,
  redirect: false,
  clientError: false,
  serverError: false,
  error: false,
  created: true,
  accepted: false,
  noContent: false,
  badRequest: false,
  unauthorized: false,
  notAcceptable: false,
  forbidden: false,
};

module.exports.dropTableDelete = {
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  body: {
    message: '',
  },
  files: undefined,
  buffered: true,
  header: {
    server: 'UsersApi',
    'content-encoding': 'gzip',
    'content-type': 'application/json',
    accepts: 'POST',
    date: 'Tue, 13 Nov 2018 19:06:19 GMT',
    connection: 'close',
    'transfer-encoding': 'chunked',
  },
  statusCode: 204,
  status: 204,
  statusType: 2,
  info: false,
  ok: true,
  redirect: false,
  clientError: false,
  serverError: false,
  error: false,
  created: true,
  accepted: false,
  noContent: false,
  badRequest: false,
  unauthorized: false,
  notAcceptable: false,
  forbidden: false,
};
